apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp
  labels:
    app: webapp
    tier: frontend
    env: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
      tier: frontend
      env: development
  # template definition for the pods
  template:
    metadata:
      labels:
        app: webapp
        tier: frontend
        env: development
    spec:
      containers:
      - name: webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5-arm64
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Pod
metadata:
  name: queue
  labels:
    app: queue
spec:
  containers:
  - name: queue
    image: richardchesterwood/k8s-fleetman-queue:release1-arm64
    resources:
      requests:
        memory: 500Mi
        cpu: 200m
      limits:
        memory: 1000Mi
        cpu: 400m
