apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  selector:
    app: webapp

  ports:
  - name: http
    port: 80
    nodePort: 30080

  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  # Critical! Unique key for the service instance.
  name: fleetman-queue
spec:
  selector:
    app: queue

  ports:
  - name: http
    # Admin console is running on port 8161
    port: 8161
    nodePort: 30010

  - name: endpoint
    port: 61616

  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  # Critical! Unique key for the service instance.
  name: fleetman-position-tracker
spec:
  selector:
    app: position-tracker

  ports:
  - name: http
    # Expose the service to other pods
    port: 8080

  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  # Critical! Unique key for the service instance.
  name: fleetman-api-gateway
spec:
  selector:
    app: api-gateway

  ports:
  - name: http
    port: 8080
    # nodePort: 30088

  # type: NodePort
  type: ClusterIP
