apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    name: hello-pod
spec:
  containers:
  - name: ubuntu
    image: ubuntu:trusty
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command:
    - "echo"
    args:
    - "Hello world"
